# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pr:
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      python -m pip install --upgrade pip
       pip install -r requirements.txt
  displayName: 'dependence install'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pytest tests/ --junitxml=pytest-results.xml'
  displayName: 'Run Pytest'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Triggering Azure Function via GET..."
      RESPONSE=$(curl -s -w "\nHTTP Status: %{http_code}\n" -X GET "${AZURE_FUNCTION_URL}")
      echo "Azure Function Response:"
      echo "$RESPONSE"
  displayName: 'AI Alanyser'


